// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicPaziresh24Avatar,
  DefaultPaziresh24AvatarProps
} from "./plasmic/paziresh_24_design_system/PlasmicPaziresh24Avatar";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { PIC_USER_IMAGE_FALLBACK_URL } from "@/common/utils/picUserImageUrl";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface Paziresh24AvatarProps extends Omit<DefaultPaziresh24AvatarProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultPaziresh24AvatarProps altogether and have
// total control over the props for your component.
export interface Paziresh24AvatarProps extends DefaultPaziresh24AvatarProps {}

function Paziresh24Avatar_(
  props: Paziresh24AvatarProps,
  ref: HTMLElementRefOf<"div">
) {
  const [src, setSrc] = React.useState(props.src);
  const [usedFallback, setUsedFallback] = React.useState(false);

  React.useEffect(() => {
    setSrc(props.src);
    setUsedFallback(false);
  }, [props.src]);

  const handleImageError = () => {
    if (!usedFallback && src !== PIC_USER_IMAGE_FALLBACK_URL) {
      setUsedFallback(true);
      setSrc(PIC_USER_IMAGE_FALLBACK_URL);
      return;
    }
    setSrc(undefined);
  };

  return (
    <PlasmicPaziresh24Avatar
      root={{ ref }}
      {...props}
      src={src}
      img={{ onError: handleImageError }}
    />
  );
}

const Paziresh24Avatar = React.forwardRef(Paziresh24Avatar_);
export default Paziresh24Avatar;
